export const designSystem = {
  name: "Makerweb System",
  summary:
    "Makerweb color and type on an Attio-style SaaS canvas: dark glass nav, centered hero, product chrome, logo marquee, and bento features.",
  principles: [
    {
      title: "Dark product canvas",
      text: "Void #141413 is the page. Surfaces raise with hairline borders and a soft inner highlight — closer to a product marketing site than a poster.",
    },
    {
      title: "Flame, not terracotta",
      text: "Primary is #FF5010. The mark also carries sun #FFDD29, lagoon #2AA1B1, and reef #167D7F. Grey #808080 is for industrial logos only.",
    },
    {
      title: "Tight SaaS chrome",
      text: "Cards sit at 18px. CTAs are pills. Logo tiles stay 2px. Radius is modest on purpose — not blob-shaped, not zero.",
    },
    {
      title: "Instrument, not Geist",
      text: "Headings and body are Instrument Sans. Fragment Mono labels the system. Display is large, centered, and tightly tracked.",
    },
  ],
  sections: [
    { id: "principles", label: "Principles" },
    { id: "color", label: "Color" },
    { id: "type", label: "Type" },
    { id: "layout", label: "Layout" },
    { id: "texture", label: "Texture" },
    { id: "components", label: "Components" },
  ],
  colors: [
    {
      name: "Flame",
      token: "--flame / --primary",
      hex: "#ff5010",
      className: "bg-flame",
      invert: true,
      use: "Primary pills, live status, mark tile",
    },
    {
      name: "Flame hot",
      token: "--flame-hot",
      hex: "#ff4800",
      className: "bg-flame-hot",
      invert: true,
      use: "Hover / pressed",
    },
    {
      name: "Sun",
      token: "--sun",
      hex: "#ffdd29",
      className: "bg-sun",
      invert: false,
      use: "Mark tile, iterate status",
    },
    {
      name: "Lagoon",
      token: "--lagoon",
      hex: "#2aa1b1",
      className: "bg-lagoon",
      invert: true,
      use: "Mark tile, live status",
    },
    {
      name: "Reef",
      token: "--reef",
      hex: "#167d7f",
      className: "bg-reef",
      invert: true,
      use: "Mark tile",
    },
    {
      name: "Void",
      token: "--void / --background",
      hex: "#141413",
      className: "bg-void",
      invert: true,
      use: "Page canvas",
    },
    {
      name: "Raise",
      token: "--raise / --card",
      hex: "#272525",
      className: "bg-raise",
      invert: true,
      use: "Cards, studio chrome",
    },
    {
      name: "Steel",
      token: "--steel",
      hex: "#808080",
      className: "bg-steel",
      invert: true,
      use: "Logo marquee, meta",
    },
    {
      name: "White",
      token: "--foreground",
      hex: "#ffffff",
      className: "bg-white",
      invert: false,
      use: "Type, secondary CTA",
    },
  ],
  type: [
    {
      name: "Display",
      sample: "Digital agency for makers",
      spec: "Instrument Sans · 600 · 3–5.25rem · tracking tight · centered",
      className:
        "text-5xl font-semibold tracking-tight min-[800px]:text-7xl",
    },
    {
      name: "Title",
      sample: "Creating delightful experiences",
      spec: "Instrument Sans · 600 · 2–3rem",
      className: "text-3xl font-semibold tracking-tight min-[800px]:text-5xl",
    },
    {
      name: "Body",
      sample:
        "Building better digital experiences for physical and digital makers.",
      spec: "Instrument Sans · 400 · 16–18px · leading 1.7 · white/60",
      className: "text-base leading-7 text-white/60",
    },
    {
      name: "UI",
      sample: "Services  ·  Process  ·  About  ·  Contact us",
      spec: "Instrument Sans · 500 · 14px · pill nav",
      className: "text-sm font-medium",
    },
    {
      name: "Meta",
      sample: "01  ·  Project Brief  ·  Inspired by global makers",
      spec: "Fragment Mono · 11px · uppercase pill",
      className: "font-mono text-xs tracking-wide text-steel",
    },
  ],
  space: [
    { name: "Page width", spec: "min(92%, 1120px)", token: "container-site" },
    { name: "Header", spec: "Glass · 68px", token: "h-[4.25rem]" },
    { name: "Section", spec: "96–128px vertical", token: "py-24 / py-32" },
    { name: "Radius", spec: "10–18px cards · pills · tiles 2px", token: "--radius" },
  ],
} as const
