export const designSystem = {
  name: "Makerweb System",
  summary:
    "Sampled from makerweb.framer.website: charcoal void, flame orange, a four-square mark, Instrument Sans, and zero radius. An agency canvas — not a SaaS product console.",
  principles: [
    {
      title: "Dark first",
      text: "The page is void #141413. Surfaces raise to #272525. White is reserved for the header bar, type, and the secondary button.",
    },
    {
      title: "Flame, not terracotta",
      text: "Primary is #FF5010. The mark also carries sun #FFDD29, lagoon #2AA1B1, and reef #167D7F. Grey #808080 is for industrial logos only.",
    },
    {
      title: "Sharp chrome",
      text: "Radius is 0. Buttons are rectangles. The logo tiles are the only 2px exception.",
    },
    {
      title: "Instrument, not Geist",
      text: "Headings and body are Instrument Sans — the family already on the Framer site (Rawest is display-only and not licensed here). Fragment Mono labels the system.",
    },
  ],
  sections: [
    { id: "principles", label: "Principles" },
    { id: "color", label: "Color" },
    { id: "type", label: "Type" },
    { id: "layout", label: "Layout" },
    { id: "texture", label: "Texture" },
    { id: "components", label: "Components" },
  ],
  colors: [
    {
      name: "Flame",
      token: "--flame / --primary",
      hex: "#ff5010",
      className: "bg-flame",
      invert: true,
      use: "Primary buttons, links, mark tile",
    },
    {
      name: "Flame hot",
      token: "--flame-hot",
      hex: "#ff4800",
      className: "bg-flame-hot",
      invert: true,
      use: "Hover / pressed",
    },
    {
      name: "Sun",
      token: "--sun",
      hex: "#ffdd29",
      className: "bg-sun",
      invert: false,
      use: "Mark tile, service accents",
    },
    {
      name: "Lagoon",
      token: "--lagoon",
      hex: "#2aa1b1",
      className: "bg-lagoon",
      invert: true,
      use: "Mark tile, chips",
    },
    {
      name: "Reef",
      token: "--reef",
      hex: "#167d7f",
      className: "bg-reef",
      invert: true,
      use: "Mark tile",
    },
    {
      name: "Void",
      token: "--void / --background",
      hex: "#141413",
      className: "bg-void",
      invert: true,
      use: "Page canvas",
    },
    {
      name: "Raise",
      token: "--raise / --card",
      hex: "#272525",
      className: "bg-raise",
      invert: true,
      use: "Cards, FAQ, forms",
    },
    {
      name: "Steel",
      token: "--steel",
      hex: "#808080",
      className: "bg-steel",
      invert: true,
      use: "Client logos, meta",
    },
    {
      name: "White",
      token: "--foreground",
      hex: "#ffffff",
      className: "bg-white",
      invert: false,
      use: "Type, header bar, secondary button",
    },
  ],
  type: [
    {
      name: "Display",
      sample: "Digital agency for makers",
      spec: "Instrument Sans · 600 · 3–4.5rem · tracking −0.03em",
      className:
        "text-5xl font-semibold leading-[0.95] min-[800px]:text-7xl",
    },
    {
      name: "Title",
      sample: "Creating delightful experiences",
      spec: "Instrument Sans · 600 · 2–2.75rem",
      className: "text-3xl font-semibold min-[800px]:text-5xl",
    },
    {
      name: "Body",
      sample:
        "Building better digital experiences for physical and digital makers.",
      spec: "Instrument Sans · 400 · 16–18px · leading 1.7",
      className: "text-base leading-7 text-white/70",
    },
    {
      name: "UI",
      sample: "Services  ·  Process  ·  About  ·  Contact us",
      spec: "Instrument Sans · 500 · 14px",
      className: "text-sm font-medium",
    },
    {
      name: "Meta",
      sample: "01  ·  Project Brief  ·  Inspired by global makers",
      spec: "Fragment Mono · 12px · steel",
      className: "font-mono text-xs tracking-wide text-steel",
    },
  ],
  space: [
    { name: "Page width", spec: "min(90%, 1280px)", token: "container-site" },
    { name: "Header", spec: "White bar · 64px", token: "h-16" },
    { name: "Section", spec: "96–128px vertical", token: "py-24 / py-32" },
    { name: "Radius", spec: "0px (tiles 2px)", token: "--radius" },
  ],
} as const
